name: product_tests
description: A Flutter module
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  product_implementation:
    path: ../product_implementation
  product_testing:
    path: ../product_testing

resolution: workspace