name: network_tests
description: A Flutter module
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  network_implementation:
    path: ../network_implementation
  network_testing:
    path: ../network_testing

resolution: workspace