// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Flutist

import 'package:flutist/flutist.dart';

/// Extension for package.dependencies.xxx access
extension PackageDependenciesX on List<Dependency> {
  /// Dependency getter for dio
  Dependency get dio => firstWhere((d) => d.name == 'dio');
  /// Dependency getter for flutter_bloc
  Dependency get flutterBloc => firstWhere((d) => d.name == 'flutter_bloc');
  /// Dependency getter for equatable
  Dependency get equatable => firstWhere((d) => d.name == 'equatable');
  /// Dependency getter for mocktail
  Dependency get mocktail => firstWhere((d) => d.name == 'mocktail');
}

/// Extension for package.modules.xxx access
extension PackageModulesX on List<Module> {
  /// Module getter for network_interface
  Module get networkInterface => firstWhere((m) => m.name == 'network_interface');
  /// Module getter for network_implementation
  Module get networkImplementation => firstWhere((m) => m.name == 'network_implementation');
  /// Module getter for network_testing
  Module get networkTesting => firstWhere((m) => m.name == 'network_testing');
  /// Module getter for network_tests
  Module get networkTests => firstWhere((m) => m.name == 'network_tests');
  /// Module getter for product_interface
  Module get productInterface => firstWhere((m) => m.name == 'product_interface');
  /// Module getter for product_implementation
  Module get productImplementation => firstWhere((m) => m.name == 'product_implementation');
  /// Module getter for product_testing
  Module get productTesting => firstWhere((m) => m.name == 'product_testing');
  /// Module getter for product_tests
  Module get productTests => firstWhere((m) => m.name == 'product_tests');
  /// Module getter for product_example
  Module get productExample => firstWhere((m) => m.name == 'product_example');
  /// Module getter for cart_interface
  Module get cartInterface => firstWhere((m) => m.name == 'cart_interface');
  /// Module getter for cart_implementation
  Module get cartImplementation => firstWhere((m) => m.name == 'cart_implementation');
  /// Module getter for cart_testing
  Module get cartTesting => firstWhere((m) => m.name == 'cart_testing');
  /// Module getter for cart_tests
  Module get cartTests => firstWhere((m) => m.name == 'cart_tests');
  /// Module getter for cart_example
  Module get cartExample => firstWhere((m) => m.name == 'cart_example');
  /// Module getter for app
  Module get app => firstWhere((m) => m.name == 'app');
}
