name: flutist_microfeature_architecture_v3
description: A new Flutter project managed by Flutist.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutist: ^3.0.0
  app:
    path: app

flutter:
  uses-material-design: true

# Flutter Native Workspace configuration
# All packages inside the 'packages' directory will be managed together
workspace:
  - app
  - packages/network/network_interface
  - packages/network/network_implementation
  - packages/network/network_tests
  - packages/network/network_testing
  - features/product/product_example
  - features/product/product_interface
  - features/product/product_implementation
  - features/product/product_tests
  - features/product/product_testing
  - features/cart/cart_example
  - features/cart/cart_interface
  - features/cart/cart_implementation
  - features/cart/cart_tests
  - features/cart/cart_testing
