name: cart_tests
description: A Flutter module
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cart_implementation:
    path: ../cart_implementation
  cart_testing:
    path: ../cart_testing

resolution: workspace