name: app
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  product_implementation:
    path: ../features/product/product_implementation
  cart_implementation:
    path: ../features/cart/cart_implementation
  network_implementation:
    path: ../packages/network/network_implementation

resolution: workspace