name: product_interface
description: A Flutter module
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  network_interface:
    path: ../../../packages/network/network_interface

resolution: workspace