name: product_implementation
description: A Flutter module
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  product_interface:
    path: ../product_interface
  network_interface:
    path: ../../../packages/network/network_interface

resolution: workspace